config/routes.rb
Rails.application.routes.draw do 

  root :to => "pages#index"

  get '/profil', to:  'users#edit', as: :profil
  patch '/profil', to: 'users#update'
  
  resources :lib_core, only: [:add, :edit, :matiere, :chapter]
  resources :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit] do 
    member do
      get 'confirm'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_token :confirmation_token
  has_secure_token :password
  validates :username, 
    format: {
     with: /\A[a-zA-Z0-9_]{2,20}\z/, 
     message: 'Le pseudonyme doit contenir que des écritures alphanumériques'},
    uniqueness: {case_sensiive: false}
  validates :email,
    format: {
      with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/
    },
    uniqueness: {case_sensitive: false}

  def to_session
    {id: id}
  end

  def generate_password
    self.password = generate_token
    save!
  end

  def generate_token
    SecureRandom.hex(10)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :danger
  before_action  :only_sign_in

  private

  def only_sign_in
    if !session[:auth] || !session[:auth]['id']
      redirect_to new_user_path, danger: 'Vous n\'êtes pas encore connecté'
    end
  end
end

app/controllers/lib_core_controller.rb
class LibCoreController < ApplicationController
  def add
  end

  def edit
  end

  def matiere
  end

  def chapter
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :only_sign_in, only:  [:index]
  def index
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :only_sign_in, only: [:new, :create] 

  def new

  end

  def create
    user_params = params.require(:user)
    @user = User.where(email: user_params[:email]).first
    if @user
      if !user_params[:password]
        @user.update(password: @user.generate_token)
        UserMailer.password(@user).deliver_now
        redirect_to new_session_path, success: "Email trouvé"
      else
        if @user[:password] == user_params[:password]
          session[:auth] = @user.to_session
          redirect_to profil_path, success: "Bravo !"
        else
          redirect_to new_session_path, danger: 'Mauvais mot de passe'
        end
      end
    else
      redirect_to new_session_path, danger: 'Aucune e-mail reconnu.'
    end
  end


  def destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :only_sign_in, only:  [:new,:create,:confirm]

  def new
    @user = User.new
  end

  def create

    user_params = params.require(:user).permit(:username, :email)
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      UserMailer.confirm(@user).deliver_now
      redirect_to profil_path, success:  'Un courriel est envoyé pour valider votre compte'
    else
      render 'new'
    end
  end

  def confirm
    @user = User.find(params[:id])
    if @user.confirmation_token == params[:token]
      @user.update(confirmed: true, confirmation_token: nil)
      @user.save(validate: false)
      session[:auth] = @user.to_session
      redirect_to new_user_path, success: 'Votre compte a été validé'
    else
      redirect_to new_user_path, danger: 'Votre compte ne semble pas être validé'
    end
  end

  def edit
    @user = User.find(session[:auth]['id'])
  end

  def update
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lib_core_helper.rb
module LibCoreHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= Rails.application.config.site[:name] %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <h1><%= Rails.application.config.site[:name] %>  </h1>
        <a href="https://gnu.org">> GNU</a>
        <a href="https://lineageos.org">> Lineage OS</a>
        <a href="https://gnous.eu">> GNOUSEU</a>
    </header>
    <%= yield %>
    <footer>
			<p>Le <a href="https://github.com/mrvxo/fsf-nsi.github.io">code source</a> de ce site est disponible sur GitHub </p>
      <p>LICENSE GNU GPL V2</p>
		</footer>

  </body>
</html>

app/views/lib_core/add.html.erb
<h1>LibCore#add</h1>
<p>Find me in app/views/lib_core/add.html.erb</p>

app/views/lib_core/chapter.html.erb
<h1>LibCore#chapter</h1>
<p>Find me in app/views/lib_core/chapter.html.erb</p>

app/views/lib_core/edit.html.erb
<h1>LibCore#edit</h1>
<p>Find me in app/views/lib_core/edit.html.erb</p>

app/views/lib_core/matiere.html.erb
<h1>LibCore#matiere</h1>
<p>Find me in app/views/lib_core/matiere.html.erb</p>

app/views/pages/index.html.erb
<main>
  <div id="right-content">
    <h1 class="header">Construction du site</h1>
    <p>Bon le site est en cours de développement le temps que je puisse terminer les abses de celui-ci</p>
  </div>
  <div id="left-content">
    <h1 class="header">Mes travaux...</h1>
    <h5 class="header">BilalIScarioth a publié "III République"</h5>
    <h5 class="header">BilalIScarioth a fait des modifications sur le github</h5>
    <h5 class="header">BilalIScarioth commit sut github</h5>
  </div>
</main>

app/views/session/new.html.erb
<main>

  <% if flash[:danger] %>
    <div class="alert">
      <%=  flash[:danger] %>
    </div>
  <% end %>

  <center>
    <h1 class="header">Connexion</h1>
    <div id="div_connect">
      <%= form_for :user, url: session_index_path, html: {id: 'form_user'}  do |f| %>
        <div>
          <%= f.email_field :email, placeholder: 'Email'%>
        </div>
        <% if flash[:success] %>
          <div>
          <%= f.password_field :password, placeholder: 'Mot de passe' %>
          </div>
        <% end %>
        <div><input class="button blue" type="submit" value="M'identifier"></div>
      <% end %>
    </div>
  </center>
</main>

app/views/users/edit.html.erb
<main>
  <div id="grid">
    <div>
      <div>
        <center>
          <div id="losange"></div>
        </center>
      </div>
      <table>
        <tbody>
          <tr> Pseudo : Email </tr>
          <td> <label> <%= @user.username %> </label></td>
          <td> <label> <%= @user.email %> </label> </td>
        </tbody>
      </table>
    </div>
  </div>
</main>

app/views/users/new.html.erb
<main>
  <% if @user.errors.any?%>
    <% @user.errors.full_messages.each do |message| %>
      <div id="warning"><%= message %></div>
    <% end %>
  <% end %>

  <% if flash[:danger] %>
    <%=  flash[:danger] %>
  <% end %>

  <center>
    <h1 class="header">Inscription</h1>
    <div id="div_connect">
      <%= form_for @user, html: {id:'form_user'} do |f| %>
        <div>
          <%= f.text_field :username, placeholder: 'Pseudonyme' %>
        </div>
        <div>
          <%= f.email_field :email, placeholder: 'Email'%>
        </div>
        <div><input class="button blue" type="submit" value="M'identifier"></div>
      <% end %>
    </div>
  </center>


  <% if flash[:success] %>
    <%= flash[:success] %>
  <% end %>	
</main>